language: python
python:
  - "3.9.1"

install:
  - pip install -r requirements.txt



script:
  - pylint department_app --exit-zero
  - coverage run -m unittest discover department_app/tests
  - coverage report

after_success:
  - coveralls
